project:
  type: website
  render:
    - ./index.qmd
    - ./about.qmd
    - ./device.qmd
    - ./consortium.qmd
    - ./publications.qmd
    - ./contact.qmd
    - "!content-en/"

website:
  favicon: /assets/images/favicon.png
  title: "HealthSonar"
  navbar:
    left:
    - href: index.qmd
      text: Κεντρική
      icon: house
    - href: about.qmd
      text: Σχετικά
      icon: info-circle
    - href: device.qmd
      text: Συσκευή
      icon: broadcast-pin
    - href: consortium.qmd
      text: Κοινοπραξία
      icon: people
    - href: publications.qmd
      text: Δημοσιεύσεις
      icon: book
    - href: contact.qmd
      text: Επικοινωνία
      icon: envelope
    right:
    - icon: twitter
      href: https://twitter.com/healthsonar
    pinned: True
  margin-header: |
    ![](/assets/images/espa_logo.jpg)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full