---
title: "About"
---

The HealthSonar project is aiming to develop a system based on ultra-low energy, ultra-wideband (UWB) radio technology, to monitor sleep, gait and indoor activity, including falls. Several groups of people face problems in their daily life related to their sleep or movement which result in a reduced quality of life. Some of those groups consist of, elders, patients with sleep disorders, patients with Parkinson disease, multiple sclerosis or other neurological and movement disorders.

The device is able to monitor both low and high amplitude motion. The former is related to thorax and abdomen oscillations for the extraction of heart and respiration rate, while the latter is related to walking, and generally to body motion.

HealthSonar is an IoT device, transmitting data directly to the cloud application where personalized machine learning methods are used to analyze them, although it can also be connected to the HealthSonar mobile app to transmit data in real time and provide health-related measures to the users.

The operation of the HealthSonar device is described below:

1. Very low-power radio waves will detect, both the body movement and the subtle oscillations caused by the lungs and the heart.
1. An intelligent unit will analyze the data and extract health-related parameters while also detecting falls.
1. A mobile application will connect to the HealthSonar device and manage the system, as well as present the extracted parameters to the users.