project:
  type: website
  render:
    - ./index.qmd
    - ./about.qmd
    - ./device.qmd
    - ./consortium.qmd
    - ./publications.qmd
    - ./contact.qmd
    - "!content-en/"

website:
  favicon: /assets/images/favicon.png
  search: false
  title: "HealthSonar"
  navbar:
    left:
    - href: about.qmd
      text: Σχετικά
      icon: info-circle
    - href: device.qmd
      text: Συσκευή
      icon: broadcast-pin
    - href: consortium.qmd
      text: Κοινοπραξία
      icon: people
    - href: publications.qmd
      text: Δημοσιεύσεις
      icon: book
    - href: contact.qmd
      text: Επικοινωνία
      icon: envelope
    right:
    - icon: twitter
      text: Ακολουθήστε μας!
      href: https://twitter.com/healthsonar
    pinned: True
  page-footer: 
    right: "![](/assets/images/espa_logo.jpg){width=300 fig-alt=ESPA}"
    # center:
    #     - icon: envelope
    #       href: mailto:info@pdneurotechnology.com
    #     - icon: twitter
    #       href: https://twitter.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    header-includes: |
        <link rel="stylesheet" href="assets/fontawesome/css/fontawesome.min.css">
        <script defer src="assets/fontawesome/js/all.min.js"></script>
